triggers:
  - name: triggertestS1
    type: trigger
    version:
      counter: 635
      
  - name: triggertest444
    type: trigger
    version:
      counter: 427

  - name: triggertest544
    type: trigger
    version:
      counter: 0
