jobs:
  - name: manifest_dep1
    type: manifest
    allowPublicAccess: false
    steps:
      - IN: deploy_img  
      
  - name: manifest_dep2
    type: manifest
    allowPublicAccess: false
    steps:
      - IN: deploy_img  
      
  - name: manifest_dep3
    type: manifest
    allowPublicAccess: false
    steps:
      - IN: deploy_img  
      
      
      
  - name: release-versionn5
    type: release
    steps:
      - IN: plv2-version
      - IN: manifest_dep
      #- IN: triggerv2sp2
      - TASK: managed
#  bump: major  

  - name: runcliscript-pubrepo
    type: runCLI
    allowPublicAccess: true
    steps:
      - IN: duplicate
      #- IN: runsh-t1
      - TASK:
        - script: ls
        - script: ./IN/duplicate/gitRepo/echo.sh
  
  
  
  
  - name: langtest_u14golall_runCI
    type: runCI
  #  serial: true
    steps:
      - IN: duplicate
      - IN: manifest_dep1
     # - IN:r123env
      - IN: triggertestS1
      - TASK:
       # - script: ./IN/duplicate/gitRepo/echo.sh
        - script: ./IN/duplicate/gitRepo/echo.sh
        - script: pwd
        - script: ls
        - script: export FOO=bar
        - script: export FOO1=bar1
        - script: echo $FOO && echo $FOO1
        # - script: "node --version"
        # - script: echo "$foo"
        # - script: echo "$n1"
        # - script: echo 'new'
    #     #- script: "sudo apt-get install tree"
    # on_success:
    #   #- uname -a
    #   # - NOTIFY: myEmailS1
    #   # - NOTIFY: mySlackS1
    #   - script: echo 'infra test'
    #   - script: echo 'newtesting success'
    # # - script: ./IN/sample-script-3/gitRepo/echo.sh
    # on_failure:
    #   - script: echo 'testing1 failure'
    #   - script: echo 'failure runSh'
    #   # - NOTIFY: mySlackS1
      
  - name: langtest_u14nodall_runCI
    type: runCI
   # allowPublicAccess: false
  #  serial: true
    steps:
      - IN: duplicate
      - IN: triggertestS1
      - IN: runtest1
      - IN: manifest_dep2
      - TASK:
        - script: ./IN/duplicate/gitRepo/echo.sh
        
  - name: sample_python_runCI
    type: runCI
  #  allowPublicAccess: false
  #  serial: true
    steps:
      - IN: duplicate
      - IN: triggertestS1
      - IN: runpublic2
      - IN: manifest_dep3
      - TASK:
        - script: ./IN/duplicate/gitRepo/echo.sh
 
