triggers:
  - name: triggertestS1remove
    type: trigger
    version:
      counter: 63
      
  - name: triggertest444
    type: trigger
    version:
      counter: 427

  - name: triggertest544
    type: trigger
    version:
      counter: 0
